FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# discover-yesod API

## Users Collection [/users]

+ Attributes (array[User])

### List Users [GET /users{?page[size],page[number],friends_of}]

## User [/users/<id>]

### Retrieve a User [GET]

+ Response 200 (application/json)
    + Attributes (User)

## Places Collection [/places]

+ Attributes (array[Place])

### List Places [GET /places{?page[size],page[number],coords[x],coords[y],visited_by}]

### Create a Place [POST]

+ Attributes (Place Base)

+ Request (application/json)

+ Response 200 (application/json)
    + Attributes (Place)

## Place [/places/<id>]

### Retrieve a Place [GET]

+ Response 200 (application/json)
    + Attributes (Place)

## Discoveries Collection [/discoveries]

### List Discoveries [GET /discoveries{?page[size],page[number],user}]

### Discoveries a Place [POST]

## Discovery [/discoveries/<id>]

### Retrieve a Discovery [GET]

## Place Photo Collection [/place/<id>/photos]

### List Photo Urls [GET]

### Upload a Photo [POST]

## Leaderboard [/leaderboard]

### Get Leaderboard

+ Response 200 (application/json)
    + Attributes (User)

### 

# Data Structures

## User Base (object)

+ id: "66268" (number)

+ first_name: "Jane" (string)

+ last_name: "Doe" (string)

+ photo_medium: "http://localhost" (string)

+ discoveries: 0 (number)

## Place Base (object)

+ id: "66d68fc0-1be0-41a7-8497-d77a2d7e2805" (string)

+ name: "My Place" (string)

    Name

+ x: 12.00032 (number)

    X coordinate

+ y: 13.00021 (number)

    Y coordinate

    
## Discovery Base (object)

+ id: "66d68fc0-1be0-41a7-8497-d77a2d7e2805" (string)

+ user_id: "66d68fc0-1be0-41a7-8497-d77a2d7e2805" (string)

    Identifier of user who discovered the place

+ place_id: "66d68fc0-1be0-41a7-8497-d77a2d7e2805" (string)

    Identifier of the place
    
+ time: "2012-04-23T18:25:43.511Z" (string)

    Datetime in iso 8601 format when the place was discovered



